from database import db, User, Organisation, Receipt, ShoppingCart, HasOrg, Portfolio, HasOrgPort
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import datetime

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

with app.app_context():
    db.drop_all()
    db.create_all()

    user = User(email='artin.onson@gmail.com', first_name='Martin', last_name='Jonson', is_admin=True)
    user.set_password('supersecret')
    db.session.add(user)

    # Category är filter till front end, 1=Djur, 2=Natur, 3=Medicin & Forskning,
    # 4=Mental hälsa, 5=Mänskliga rättigheter, 6=Övrigt

    db.session.add(Organisation(name='Barncancerfonden', selector_name='Barncancerfonden', logo='images/logo_barncancerfonden.png', short_info='Barncancerfonden arbetar för att bekämpa barncancer och se till att drabbade barn och deras föräldrar får den vård och stöd de behöver. Deras högsta önskan är att alla barn som blivit drabbade av cancer ska bli friska igen. För att nå dit måste forskningen fortsätta drivas framåt.', long_info='85% av de drabbade barnen överlever sin sjukdom. Barncancer är fortfarande den vanligaste dödsorsaken i Sverige för barn i åldern 1-14 år. Barncancerfonden bildades 1982 och de hade 124 miljoner i insamlade medel 2019. ', url='https://www.barncancerfonden.se/', category = 3))
    db.session.add(Organisation(name='ActionAid', selector_name='ActionAid', logo='images/logo_actionaid.png', short_info='ActionAid är en global rättighetsorganisation som arbetar för en rättvis, jämlik och hållbar värld fri från fattigdom. De vill att kvinnor ska kunna växa upp till självständiga kvinnor med makt att forma sina egna liv och samhället de lever i.', long_info='Deras fokusområden är kvinnors och flickors rättigheter, kampen för demokratiska rättigheter, katastrofinsatser och beredskap samt hållbar försörjning och klimatanpassning. ActionAid grundades i Storbritannien 1972, och har funnits i Sverige sedan 2006. Av pengarna de får går 77% till ändamålet, 18% till insamling och 5% till administration.', url='https://www.actionaid.se/', category=5))
    db.session.add(Organisation(name='Barnfonden', selector_name='Barnfonden', logo='images/logo_barnfonden.jpg', short_info='Barnfonden är en barnrättsorganisation som arbetar i utsatta områden i Afrika, Asien och Latinamerika. Med ditt stöd kan de ge fler barn utbildning, god hälsa och trygghet i ett förenderligt klimat.', long_info='Barnfonden stödjer utvecklingsprojekt i 9 länder i Afrika, Asien och Latinamerika genom deras samarbetspartners inom ChildFund Alliance. Barnfonden grundades 1991', url='https://barnfonden.se/', category = 5))
    db.session.add(Organisation(name='Blomsterfonden', selector_name='Blomsterfonden', logo='images/logo_blomsterfonden.jpg', short_info='Blomsterfonden är en ideell förening som arbetar för hem och vård åt äldre. De arbetar för äldres bästa och deras rätt till ett tryggt hem, professionell vård och god omsorg.', long_info='Blomsterfonden bedriver sin verksamhet med hem och vård åt äldre i Stockholm och har fem seniorboenden med social verksamhet, tre äldreboenden, egen hemtjänst samt rådgivning för allmänhetn. 1921 bildades föreningen. ', url='https://www.blomsterfonden.se/', category = 5))  
    db.session.add(Organisation(name='Bröstcancerförbundet', selector_name='Bröstcancerförbundet', logo='images/logo_brostcancerforbundet.png', short_info='Bröstcancerförbundet är Sveriges enda intresseorganisation som fokuserar enbart på bröstcancer och som stödjer både forskning och medlemmar. För att de ska nå sin vision om att ingen ska drabbas av bröstcancer, finansierar de forskning, sprider kunskap kring prevention och friver opinionsbildning i börstcancerfrågor. ', long_info='Bildades 1982 och är en partipolitisk och religiöst obunden ideell patientorganisation. De arbetar, på både nationell och internationell nivå, mot bästa möjliga förutsättningar för bröstcancerdrabbade och deras närstående. ', url='https://brostcancerforbundet.se/', category = 3))  
    db.session.add(Organisation(name='Childhood', selector_name='Childhood', logo='images/logo_childhood.png', short_info='Childhood arbetar för att skydda barn från våld och sexuella övergrepp. Grundat av drottning Silvia.', long_info='Childhood ger stöd till lokala organisationer som utvecklar nya och innovativa metoder för att hjälpa utsatta barn och familjer. Med kunskap, finansiering och nätverk ger vi styrka åt idéer och innovation som skyddar barn i Sverige och i resten av världen. Detta bidrar både till långvarig systematisk förändring och förbättrar livet här och nu för det enskilda barnet.', url='https://childhood.org/', category = 5))
    db.session.add(Organisation(name='Diabetesförbundet', selector_name='Diabetesförbundet',logo='images/logo_diabetesforbundet.png', short_info='Diabetesförbundets vision är att utrota diabetes för gott, men just nu finns det inget botemedel. Just nu gör de allt för att livet med diabetes ska vara så rättvist och enkelt så möjligt. De slår hål på myter och fördomar genom att sprida kunskap. I diabetsrelaterade frågor är de en stark röst mot orättisor. ', long_info='Via diabetesfonden ger de stöd till forskning som letar efter ett svar på diabetesgåtan. De förenklar vardagen hos dem som drabbats av diabetes genom att sprida inspiration om egenvård. De bildades 1943.', url='https://www.diabetes.se/', category = 3))  
    db.session.add(Organisation(name='Dispurse Foundation', selector_name='Dispurse-Foundation', logo='images/logo_dispurse.png', short_info='Dispurse är en stiftelse vars syfte är att bekämpa fattigdom genom utbildning, de är politiskt och religiöst oberoende. Deras primära målgrupp är kvinnor i åldern 20-44 år som lever i utsatta områden i Latinamerika, men de utesluter ingen. ', long_info='De utvecklar innovativa, individanpassade och kostnadseffektiva läromedel för vuxna för att ge dem möjlighet att bättre klara sin vardag, förbättra sin ekonomiska situation och ge dem möjlighet till att aktivt vara med och utveckla det samhälle de lever i. Deras arbete startades 1993.', url='https://dispurse.org/', category = 5))  
    db.session.add(Organisation(name='Djurens Rätt', selector_name='Djurens-Rätt', logo='images/logo_djurensratt.jpg', short_info='Djurens Rätt arbetar för att alla djur som lider i djurförsök, i livsmedelindustrins djurfabriker, i burar på pälsfarmer och djur som på andra sätt utnyttjas av människor så att de inte får utlopp för sina naturliga beteenden.', long_info='De arbetar genom demokratisk opinionsbildning, politisk påverkan och attitydförändring för att skapa en värld där djur respekteras som kännande individer med rätt till sina egna liv. De har funnits sedan 1882 och är idag Sveriges ledande djurrätts- och djurskyddsorganisation. ', url='https://www.djurensratt.se/', category = 1))  
    db.session.add(Organisation(name='Friends', selector_name='Friends', logo='images/logo_friends.jpg', short_info='Friends är en barnrättsorganisation utan vinstsyfte som vill skapa en värld utan mobbning. Där varje barn känner sig älskat och respekterat. Där ingen somnar ledsen, vaknar med ångest och går hemifrån med en klump i magen.', long_info='De arbetar tvärvetenskapligt, med en kombination av forkning och beprövad erfarenhet. De samarbetar med skolor, förskolor och idrottsföreningar i hela Sverige. De har ett mål, att inte ett enda barn ska utsättas för mobbning.', url='https://friends.se/', category = 4))  
    db.session.add(Organisation(name='Hjärnfonden', selector_name='Hjärnfonden', logo='images/logo_hjarnfonden.jpg', short_info='Hjärnfondends vision är att ingen ska behöva lida av sjukdomar, skador eller funktionsnedsättningar i hjärnan. Det är en ideell insamlingsstiftelse utan statligt stöd, som har till uppgift att samla in och fördela pengar till forskning samt informera om hela hjärnan och alla dess sjukdomar, skador och funktionsnedsättningar. ', long_info='Målet är att hitta nya, effektiva behandlingar samt att intensifiera livsviktig forskning. Stiftelsen bildades 1994. De kunde 2018 dela ut 83,4 miljoner kronor till hjärnforskare i Sverige. ', url='https://www.hjarnfonden.se/', category = 3))  
    db.session.add(Organisation(name='Hoppets Stjärna', selector_name='Hoppets-Stjärna', logo='images/logo_hoppetsstjarna.png', short_info='Hoppets Stjärna hjälper fattiga barn och deras närmiljö att utveckla sina möjligheter så att de själva kan påverka sina liv och samhället de lever i. Detta görs genom bland annat utbildning, hälsovård och näringsriktig mat.', long_info='Visionen är att skapa en värld där alla barn får utvecklas som människor, obundna av fattigdom i alla dess former. Hoppets Stjärna samarbetar med lokala partners i alla biståndsländer och arbetar tillsammans med kontakter i utvecklingen av biståndsarbetet och analys av behoven.', url='https://www.starofhope.se/', category = 5))  
    db.session.add(Organisation(name='Human Bridge', selector_name='Human-Bridge', logo='images/logo_humanbridge.jpg', short_info='Human Bridge är en svensk biståndsorganisation som arbetar för människa och miljö. Genom insamling och leverans av väl genomgången itrangerad sjukvårdsutrustning, begagnade textilier samt förnödenheter skapas bättre förutsättningar för människor i utsatta länder och en rättvisare resursfördelning. ', long_info='Årligen sker insatser till ett 25-tal länder och främst i länder i Afrika, Östeuropa och Mellanöstern. De bildades 2001 och finansieras delvis genom förädling och försäljning av textilier, en mindre del kommer från grundarna och från allmänheten. De vill genon sitt arbete vara med och göra skillnad för både människa och miljö.', url='http://www.humanbridge.se/', category = 3)) 
    db.session.add(Organisation(name='Hundstallet', selector_name='Hundstallet', logo='images/logo_hundstallet.png', short_info='Hundstallets uppgift är at thjälpa, vårda och omplacera utsatta hundar. De tar emot hundar 24 timmar om dygnet, sju dagar i veckan, året om. De får inga statliga bidrag utan finansieras helt av gåvor från allmänheten. ', long_info='De bildades 1908 och finns i Stockholm och Skåne samt kommer snart finnas i Västra Götaland. De tar nu emot cirka 500 hundar om året och kommer kunna dubblera det med utökningen. ', url='https://hundstallet.se/', category = 1)) 
    db.session.add(Organisation(name='Kids Future', selector_name='Kids-Future', logo='images/logo_kidsfuture.png', short_info='Kids Future arbetar med och för barn och ungdomar. Deras huvudsakliga samarbetspartner är Kids Ark Foundation i norra Thailand, som driver ett fritidshem dit barn kommer efter skolan för att få läxhjälp, ny kunskap och mat. ', long_info='Deras engagemang grundar sig i att alla ska ha möjligheten att utvecklas till sin fulla potential. Oavsett var i världen en är född. De vill bidra till en värld där fler ges möjlighet att leva sina liv utifrån sina livsvärderingar och drömmar. De grundades 2002. ', url='https://kidsfuture.se/', category = 5)) 
    db.session.add(Organisation(name='Mentor', selector_name='Mentor', logo='images/logo_mentor.png', short_info='Mentor Sverige är en ideell organisation som arbetar med mentorskap för ungdomar. Alla ungdomar i Sverige behöver ett par fotspår att gå i och en person att inspireras av. De har en vision är en värld där unga får växa och utvecklas hälsosamt och drogfritt. ', long_info='Mentor Sverige ingår i Mentor International, de finns även i Mellanöstern, USA, Tyskland, Danmark och Baltikum. De genomför även projekt i 70 länder genom olika fältorganisationer. Sedan 1994 har Mentor nått över 2,5 miljoner barn och ungdomar.', url='https://mentor.se/', category = 6)) 
    db.session.add(Organisation(name='Mind', selector_name='Mind', logo='images/logo_mind.jpg', short_info='Mind arbetar för ett samhälle som uppmärksammar och aktivt motverkar psykisk ohälsa, där personer med psykisk ohälsa blir respekterade och får det stöd de behöver, och där ingen tar sitt liv. De förebygger psykisk ohälsa genom att erbjuda medmänskligt stöd, sprida kunskap och bilda opinion. ', long_info='Mind grundades 1931 och har idag lokala avdelningar i Halmstad, Göteborg, Malmö, Stockholm och Umeå där de har Självmordslinjer. ', url='https://mind.se/', category = 4)) 
    db.session.add(Organisation(name='Naturskyddsföreningen', selector_name='Naturskyddsföreningen', logo='images/logo_naturskyddsforeningen.jpg', short_info='Naturskyddsföreningen är Sveriges största ideella miljöorganisation. De arbetar för att naturen ska bli friskare så att människor i hela världen ska kunna må bra.', long_info='Naturskyddsföreningar arbetar inom områdena: Hav & vatten, Jordbruk & mat, Klimat, energi och transporter, Miljögifter samt Skog & naturvård. Genom politisk påverkan, naturkänsla samt konsumentmakt kämpar Naturskyddsföreningen för att få med alla på tåget, för bara då kan planeten räddas. Naturskyddsföreningen har tagit fram miljömärkningen Bra Miljöval som hjälper dig att välja de produkter som är minst skadliga för miljön.', url='https://www.naturskyddsforeningen.se/', category = 2))  
    db.session.add(Organisation(name='Neuroförbundet', selector_name='Neuroförbundet', logo='images/logo_neuro.png', short_info='Neuro är en oberoende organisation specialiserad på neurologi. De finns för att ge information, stöd och en framtidstro. Deras mål är att personer som lever med neurologiska diagnoser ska få samma möjligheter, rättigheter och skyldigheter som alla andra. ', long_info='Neuros uppdrag består av tre delar: Bilda opinion, stöd till medlemmar och bidrag till forskning. De bildades 1957.', url='https://neuro.se/', category = 3))  
    db.session.add(Organisation(name='PMU', selector_name='PMU', logo='images/logo_PMU.png', short_info='PMU, står för Pingsmissionens utvecklingssamarbete, är en av Sveriges största biståndsorganisationer. De vill bekämpa fattigdom i alla dess former genom att samverka med människor i utsatthet. Detta gör de genom långsiktiga utvecklingsprojekt och humanitära insatser. ', long_info='Deras uppdrag är också att generera resurser och fördjupa engagemanget för rättvisa och upprättelse. De bildades 1965 och arbetar idag med ungefär 172 projekt i cirka 27 olika länder. ', url='https://pmu.se/', category = 5))  
    db.session.add(Organisation(name='Skandinaviska Läkarbanken', selector_name='Skandinaviska-Läkarbanken', logo='images/logo_slb.png', short_info='Skandinaviska Läkarbankens uppdrag är att bedriva hjälpverksamhet i låginkomstländer genom att medicinsk personal - i första hand läkare - ställer sig till förfogande för att oavlänade arbeta där. De bedriver även informationsverksamhet och bildning om behovet av medicinska insatser och låginkomstländernas situation.', long_info='Deras målsättning är att utifrån en kristen livssyn arbeta för att människor i låginkomstländer skall ha tillgång till hälso- och sjukvård anpassad efter sina behov. De sänder ut årligen mer än 50 personer.', url='https://skandinaviskalakarbanken.se/', category = 5))  
    db.session.add(Organisation(name='SOS Barnbyar', selector_name='SOS-Barnbyar', logo='images/logo_sosbarnbyar.png', short_info='SOS Barnbyar är en världsomspännande barnrättsorganisation som verkar i 136 länder för att trygga barns nutid – och framtid. SOS Barnbyar arbetar för att inget barn ska växa upp ensamt utan istället växa upp med nära relationer så att de kan bli sitt starkaste jag.', long_info=' Arbetet innefattar förebyggande insatser, barnbyar, hälsa och sjukvård, utbildning, katastrofinsatser och arbete för barns rättigheter. Den svenska verksamheten är framförallt inriktad på insamling, kommunikation och påverkansarbete – för att driva utvecklingen av internationella riktlinjer och policys inom federationen. Bildades 1949.', url='https://sos-barnbyar.se/', category = 5))  
    db.session.add(Organisation(name='Spädbarnsfonden', selector_name='Spädbarnsfonden', logo='images/logo_spadbarnsfonden.png', short_info='Spädbarnsfonden stödjer familjer som har förlorat barn, samt deras anhöriga och personer i deras närhet som behöver stöd. Spädbarnsfondens vision är att inget spädbarn ska dö av förhållanden som kan upptäckas och där medicinsk kunskap för åtgärd finns tillgänglig.', long_info='Spädbarnsfonden arbetar med en rad olika stödfunktioner så som samtalsgrupper, minnesstund och familjehelger för föräldrar som mist ett barn. Spädbarnsfonden bedriver också påverkansarbete och arbetar för att påverka att alla gravida ska få information om fosterrörelser, lika bemötande i hela landet och fler föräldrapenningdagar till drabbade föräldrar. Bildades 1986.', url='https://www.spadbarnsfonden.se/', category = 6))  
    db.session.add(Organisation(name='Stockholms Stadsmission', selector_name='Stockholms-Stadsmission', logo='images/logo_stockholmsstadsmission.png', short_info='Stockholms Stadsmission arbetar för ett mänskligare samhälle genom social omsorg, arbetsintegration och utbildning. Målet är att främja delaktighet oavsett ekonomi och bakgrund och att förebygga utanförskap.', long_info='Stockholms Stadsmission har i huvudsak tre verksamhetsområden.  Social verksamhet: enheter som driver verksamhet för ban & unga, familjer, vuxna och äldre i utsatthet t.ex. Unga Station, Terapicenter för unga och Crossroads råd- och stödcenter.   Sociala företag: secondhand butiker och Grillska Husets verksamhet.   Skolverksamhet: folkhögskola, gymnasieskola, gymnasiesärskola, komvux och yrkeshögskola', url='https://www.stadsmissionen.se/', category = 5))  
    db.session.add(Organisation(name='Suicide Zero', selector_name='Suicide-Zero', logo='images/logo_suicidezero.png', short_info='Suicide Zero är en ideell organisation som arbetar för att radikalt minska självmorden i Sverige. Vision: ett samhälle utan självmord.', long_info='Suicide Zero arbetar för att minska tabun kring självmord och psykisk ohälsa, och de visar på nytänkande och konkreta lösningar för att rädda liv. De sprider information för att öka allmänhetens kunskap och bildar opinion kring självmord. Suicide Zeros mål är att varje kommun i Sverige ska ha sin egen handlingsplan för hur självmorden ska minska. Grundades 2013.', url='https://www.suicidezero.se/', category = 4))  
    db.session.add(Organisation(name='Svalorna Indien Bangladesh', selector_name='Svalorna-Indien-Bangladesh', logo='images/logo_svalorna.png', short_info='Svalorna Indien Bangladesh bekämpar fattigdom, diskriminering och dess orsaker. Tillsammans med lokala organisationer gör de det möjligt för människor att stå upp för sina rättigheter, att ta sig ur fattigdom och skapa sig ett bättre liv.', long_info='Svalorna Indien Bangladesh arbetar tillsammans med de som själva är drabbade av fattigdom och orättvisor. De tror på en förändring där människor själva får möjligheten att påverka sitt liv och det samhälle de lever i och att det är vägen till en hållbar och rättvis utveckling. Fokusområden: Lika rättigheter mellan könen, Försörjning & småjordbrukares rättigheter, Hållbarhet och Rättigheter för utsatta grupper', url='https://svalorna.org/', category = 5))  
    db.session.add(Organisation(name='Svenska Freds- och Skiljedomsföreningen', selector_name='Svenska-Freds-och-Skiljedomsföreningen', logo='images/logo_svenskafreds.png', short_info='Svenska Freds- och Skiljedomsföreningen är en ideell förening som arbetar för hållbar fred genom att sprida kunskap, bilda opinion och påverka politiker. Vision: hållbar fred i världen.', long_info='Svenska Freds- och Skiljedomsföreningen grundades 1883 och är Sveriges största och världens äldsta ännu aktiva fredsförening. Genom att granska och påverka beslutsfattare, stödja fredskrafter i internationella samarbeten och lokala fredsorganisationer i konfliktområden skapar de engagemang, förutsättningar för och visioner i det gemensamma arbetet för hållbar fred i världen. Svenska Freds verkar för: Hållbar fred, Demokrati och mänskliga rättigheter, Fredlig konflikthantering, Internationell rätt och Nedrustning.', url='https://www.svenskafreds.se/', category = 6))  
    db.session.add(Organisation(name='Svenska Hästars Värn', selector_name='Svenska-Hästars-Värn', logo='images/logo_shv.png', short_info='Svenska Hästars Värn bedriver en rikstäckande räddningsverksamhet för alla hästar som inte får sina primära behov, såsom foder och vatten, tillgodosedda.', long_info='Svenska Hästars Värn är Sveriges enda djurskyddsorganisation för hästar. De tar emot hästar som omhändertagits av myndigheter och placerar dem i akuthem hos en volontär. De rehabiliterar hästarna fysiskt, mentalt och känslomässigt och placerar därefter ut dem i noga utvalda trygga foderhem. Deras ambition är att i framtiden ha ett eller flera räddningscenter där hästar i behov av vård kan komma i väntan på att placeras i foderhem.', url='https://shv.org/', category = 1))  
    db.session.add(Organisation(name='Svenska Läkare mot Kärnvapen', selector_name='Svenska-Läkare-mot-Kärnvapen', logo='images/logo_slmk.png', short_info='Svenska Läkare mot Kärnvapen arbetar för att kärnvapen ska förbjudas och avskaffas, genom att informera om kärnvapnens medicinska konsekvenser. De vill göra en säkrare framtid fri från kärnvapen möjlig.', long_info='Svenska Läkare mot Kärnvapen genomför regelbundet olika projekt med koppling till kärnvapen och nedrustning. De deltar i internationella och nationella möten och förhandlingar om kärnvapen och sprider information, ny kunskap och analyser kring kärnvapenpolitik och kärnvapens medicinska effekter på olika sätt. För deras arbete har de mottagit två Nobels fredspris.', url='https://slmk.org/', category = 6))  
    db.session.add(Organisation(name='Sveriges Dövas Riksförbund', selector_name='Sveriges-Dövas-Riksförbund', logo='images/logo_sdr.png', short_info='Sveriges Dövas Riksförbund driver frågor om dövas mänskliga och demokratiska rättigheter. Deras vision är teckenspråk för möjligheter utan gränser och ett hållbart samhälle. ', long_info='Verksamheten erbjuder teckenspråkiga mötesplatser och sprider kompetens och medvetenhet inom organisationen och i det omgivande samhället. Det finns cirka 30.000 döva och hörselskadade personer i landet som kommunicerar med svenskt teckenspråk. Ännu idag har inte teckenspråkiga döva barn, ungdomar och vuxna självklar rätt till förskola, utbildning, arbete, tolk, kultur, social omsorg och äldrevård på sitt språk, teckenspråk.', url='https://sdr.org/', category = 5))  
    db.session.add(Organisation(name='Ung Cancer', selector_name='Ung-Cancer', logo='images/logo_ungcancer.svg', short_info='Ung Cancer är en ideell organisation som finns till för unga vuxna som själva drabbats eller lever nära någon som drabbats av cancer.', long_info='Ung Cancer finns till för sina medlemmar genom att ge psykosocialt stöd och fylla det gap som ofta uppstår mellan livet på sjukhuset och livet utanför. De skapar mötesplatser och kan ge ekonomiskt stöd samt stöttar sina medlemmar i sin rehabilitering och skapar vägar vidare.', url='https://ungcancer.se/', category = 3))
    db.session.add(Organisation(name='Vi-skogen', selector_name='Vi-skogen', logo='images/logo_viskogen.png', short_info='Vi-skogen är en biståndsorganisation som planterar träd i östra Afrika som motverkar fattigdom och klimatförändringar.', long_info='Genom att odla träd tillsammans med grödor i jordbruket kan familjer tjäna pengar nog att investera för framtiden. Vision: En hållbar miljö som möjliggör för kvinnor och män som lever i fattigdom att förbättra sina liv.', url='https://viskogen.se/', category = 2))

    db.session.add(ShoppingCart(summation=450, user_email='artin.onson@gmail.com'))
    db.session.add(HasOrg(shopping_id=1, organisation_id=28, percentage=0.20))
    db.session.add(HasOrg(shopping_id=1, organisation_id=18, percentage=0.40))
    db.session.add(HasOrg(shopping_id=1, organisation_id=32, percentage=0.40))
    db.session.add(Receipt(time_of_purchase=datetime.datetime.now(), user_email='artin.onson@gmail.com', shopping_cart_id=1))

    db.session.add(ShoppingCart(summation=200, user_email='artin.onson@gmail.com'))
    db.session.add(HasOrg(shopping_id=2, organisation_id=31, percentage=0.75))
    db.session.add(HasOrg(shopping_id=2, organisation_id=5, percentage=0.25))
    db.session.add(Receipt(time_of_purchase=datetime.datetime.now(), user_email='artin.onson@gmail.com', shopping_cart_id=2))

    # PORTFOLIOS:
    db.session.add(Portfolio(name="Framtidsfonden", logo='https://www.ekenhalsan.se/wp-content/uploads/2014/05/symbol-barn.png', 
    short_info='I denna portfölj ligger fokus på att hjälpa barn i olika situationer, både i Sverige och runt om i världen. Den innehåller nio organisationer som har samma fördelning. '))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=1))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=3))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=6))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=10))

    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=12))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=15))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=16))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=22))
    db.session.add(HasOrgPort(portfolio_id=1, organisation_id=23))

    db.session.add(Portfolio(name="Djurvännen", logo='https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Paw_%28Animal_Rights_symbol%29.svg/1024px-Paw_%28Animal_Rights_symbol%29.svg.png', 
    short_info='Det här är portföljen för dig som sätter djuren först. I portföljen "Djurvännen" så ingår det 3 stycken organsisationer som jobbar mot att alla djur ska få de dem förtjänar. Fördelningen är lika mellan alla organisationer i portföljen.'))
    db.session.add(HasOrgPort(portfolio_id=2, organisation_id=9))
    db.session.add(HasOrgPort(portfolio_id=2, organisation_id=14))
    db.session.add(HasOrgPort(portfolio_id=2, organisation_id=28))
    
    db.session.add(Portfolio(name="Hjälp naturen", logo='https://www.pngkit.com/png/detail/106-1062919_the-tree-of-life-symbol-tree-symbol.png', 
    short_info='Denna portfölj innehåller organisationer som arbetar mot en friskare värld och ett klimat som gynnar människorna i närområdet samt moder jord.'))
    db.session.add(HasOrgPort(portfolio_id=3, organisation_id=18))
    db.session.add(HasOrgPort(portfolio_id=3, organisation_id=32))

    db.session.add(Portfolio(name="Mot diabetes tillsammans med Jihde", logo='https://www.doktorn.com/wp-content/uploads/2020/05/shutterstock_715778998-870x489.jpg', 
    short_info='Vi på DoneraMera har skapat denna portfölj för att backa Jihde i hans fantastiska kamp i att uppmärksamma sig själv och hans diabetes.'))
    db.session.add(HasOrgPort(portfolio_id=4, organisation_id=7))
    db.session.commit()

    db.session.commit()
